### ISSUE TITLE
BitView.buffer is no longer changed as BitView._view changes

### ISSUE THREAD

**Issue by ceineke** [inolen/bit-buffer#1]
node v0.10 has changed the behaviour when creating a Uint8Array with a Buffer. It no longer shares the reference, but clones the buffer. That means any changes made with writeBits is not reflect in the buffer property.

**Comment by MatthewBarker** [comment]
Any chance of merging this please?

**Comment by inolen** [comment]
Heh, yep, just flipped through the cracks.
