### ISSUE TITLE
Update npm package

### ISSUE THREAD

**Issue by AppLover69** [inolen/bit-buffer#10]
npm package is older than GitHub version.

**Comment by inolen** [comment]
The real problem is just that I haven't setup and used npm in ages now (I haven't been working with JS the past few years). If @icewind1991 would like to, I can work to transfer ownership over to him.

**Comment by icewind1991** [comment]
Fine by me

**Comment by AppLover69** [comment]
Keeping this package active would be great.

**Comment by inolen** [comment]
@icewind1991 what's your username on npm?

**Comment by icewind1991** [comment]
icewind1991

**Comment by inolen** [comment]
@icewind1991 you're a contributor on the github project and an owner on the npm package now :+1:

**Comment by icewind1991** [comment]
Ok, I'll do some polishing and tags a release soon

**Comment by icewind1991** [comment]
@inolen can you enable travis-ci for the repo (or give me the admin permissions needed to do it)

**Comment by inolen** [comment]
Enabled +1

**Comment by icewind1991** [comment]
New version tagged and published.
